stages:
  - install
  - build
  # - test
  - deploy

services:
  - docker:dind

# Cache modules in between jobs
cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - .npm/

build:code:
  stage: install
  image: decentraland/ci-node:latest
  variables:
    PULUMI_STACK: "website-events"
  only:
    - master
    - staging
    - release
  script:

    # install dependencies
    # - npm ci --cache .npm --prefer-offline
    - npm i decentraland-gatsby-deploy

    # setup dcl environment
    - export PATH="$PATH:$HOME/.pulumi/bin"
    - source dcl-env

    # setup project environment
    - pulumi login -c "s3://$STATE_BUCKET/"
    - >
      if pulumi stack select "$PULUMI_STACK-$ENVIRONMENT"; then
        echo "[stack $stack] Stack exists ✅";
      else
        pulumi stack init "$PULUMI_STACK-$ENVIRONMENT"
        echo "[stack $stack] Stack created ✅";
      fi

    - source ./node_modules/.bin/setup-environment

    - env | grep GATSBY_ > .env
    - echo .env

    - docker build -t events .
    - docker cp "events:/app/public" "./public"
    - ls -alh "./public"
    # build source
    # - npm run build

    # push server
    # - dcl-lock-sync
    # - dcl-up $PULUMI_STACK
    # - dcl-sync-release

    # # push static
    # - docker cp "$(pulumi stack output serviceImage):/app/public" "./public"
    # - ./node_modules/.bin/setup-bucket public
    # - dcl-cache-invalidation
