stages:
  - install
  - build
  # - test
  - deploy

services:
  - docker:dind

# Cache modules in between jobs
cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - .npm/

build:code:
  stage: install
  image: decentraland/ci-node:latest
  variables:
    PULUMI_STACK: "website-events"
  only:
    - master
    - staging
    - release
  script:

    # install dependencies
    - npm install --cache "$CI_PROJECT_DIR/.npm" --prefer-offline

    # setup dcl environment
    - export PATH="$PATH:$HOME/.pulumi/bin"
    - source dcl-env

    # setup project environment
    - pulumi login -c "s3://$STATE_BUCKET/"s
    - >
        if pulumi stack --cwd .ci select "$PULUMI_STACK-$ENVIRONMENT" then
          echo "[stack $stack] Stack exists ✅";
        else
          pulumi stack --cwd .ci init "$PULUMI_STACK-$ENVIRONMENT"
          echo "[stack $stack] Stack created ✅";
        fi

    - source ./node_modules/.bin/pulumi-environment

    # build source
    - npm run build

    # build docker
    - export CI_REGISTRY_IMAGE="$CI_REGISTRY_REPOSITORY_AWS/events:$CI_COMMIT_SHA"
    - aws ecr get-login-password --region $CI_REGISTRY_REGION | docker login --username AWS --password-stdin "$CI_REGISTRY_REPOSITORY_AWS"
    - DOCKER_BUILDKIT=1 docker build --pull -t $CI_REGISTRY_IMAGE .

    # push docker
    - docker push $CI_REGISTRY_IMAGE

    # push server
    - cd .ci && npm install --cache "$CI_PROJECT_DIR/.npm" --prefer-offline
    - dcl-lock-sync
    - dcl-up $PULUMI_STACK
    - dcl-sync-release

    # push static
    - cd .. && dcl-upload public
    - cd .ci && dcl-cache-invalidation
    - cd ..
