stages:
  - install
  - build
  # - test
  - deploy

services:
  - docker:dind

build:code:
  stage: install
  image: decentraland/ci-node:latest
  variables:
    PULUMI_STACK: "website-events"
  only:
    - master
    - staging
    - release
  script:

    # install dependencies
    # - npm ci --cache .npm --prefer-offline
    - npm i -g npm@8
    - npm i decentraland-gatsby-deploy
    - ls node_modules
    - ls node_modules/@pulumi

    # setup dcl environment
    - export PATH="$PATH:$HOME/.pulumi/bin"
    - source dcl-env

    # setup project environment
    - pulumi login -c "s3://$STATE_BUCKET/"
    - >
      if pulumi stack select "$PULUMI_STACK-$ENVIRONMENT"; then
        echo "[stack $stack] Stack exists ✅";
      else
        pulumi stack init "$PULUMI_STACK-$ENVIRONMENT"
        echo "[stack $stack] Stack created ✅";
      fi

    - source ./node_modules/.bin/setup-environment

    - env | grep GATSBY_ > .env
    - echo .env

    # push server
    - dcl-lock-sync
    - dcl-up $PULUMI_STACK
    - dcl-sync-release

    # # push static
    - mkdir ./public
    - docker run -v $PWD:/data --rm --entrypoint cp $(pulumi stack output serviceImage) -r '/app/public' '/data'
    - ./node_modules/.bin/setup-bucket public
    - dcl-cache-invalidation
