stages:
  - install
  - build
  # - test
  - deploy

services:
  - docker:dind

# Cache modules in between jobs
cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - .npm/

build:code:
  stage: install
  image: decentraland/ci-node:latest
  variables:
    PULUMI_STACK: "website-events"
  only:
    - master
    - staging
    - release
  script:

    # install dependencies
    - npm ci --cache .npm --prefer-offline

    - ./node_modules/.bin/setup-stack
    - source ./node_modules/.bin/setup-environment

    # build source
    - npm run build

    # build docker
    - export CI_REGISTRY_IMAGE="$CI_REGISTRY_REPOSITORY_AWS/events:$CI_COMMIT_SHA"
    - aws ecr get-login-password --region $CI_REGISTRY_REGION | docker login --username AWS --password-stdin "$CI_REGISTRY_REPOSITORY_AWS"
    - DOCKER_BUILDKIT=1 docker build --pull -t $CI_REGISTRY_IMAGE .

    # push docker
    - docker push $CI_REGISTRY_IMAGE

    # push server
    - dcl-lock-sync
    - dcl-up $PULUMI_STACK
    - dcl-sync-release

    # push static
    - ./node_modules/.bin/setup-stack public
    - dcl-cache-invalidation
